{"name": "test01_combo", "status": "failed", "statusDetails": {"message": "Failed", "trace": "self = <test_case.test_calculator.TestCalculator object at 0x000002A888B47AF0>\n\n    def test01_combo(self):\n>       pytest.fail()\nE       Failed\n\ntest_calculator.py:11: Failed"}, "start": 1640694979609, "stop": 1640694979609, "uuid": "32bf88f5-f9e2-477f-9fac-3820a6c702b9", "historyId": "9c948d6f5db5edbaef64d52f8bbc4041", "testCaseId": "203845d71053675a32f5762b16cf14ee", "fullName": "test_calculator.TestCalculator#test01_combo", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_desktop')"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-2U5JCBG"}, {"name": "thread", "value": "25268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}