{"name": "test01_combo", "status": "failed", "statusDetails": {"message": "Failed", "trace": "self = <test_case.test_calculator.TestCalculator object at 0x000001490039BB20>\n\n    def test01_combo(self):\n>       pytest.fail()\nE       Failed\n\ntest_calculator.py:11: Failed"}, "attachments": [{"source": "e69adb0c-c4fe-4331-90a4-c275b1e0d29f-attachment.png", "type": "image/png"}], "start": 1640699885629, "stop": 1640699885629, "uuid": "6fb4611e-a790-459a-adc7-fdedc129fa82", "historyId": "9c948d6f5db5edbaef64d52f8bbc4041", "testCaseId": "203845d71053675a32f5762b16cf14ee", "fullName": "test_calculator.TestCalculator#test01_combo", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_desktop')"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-2U5JCBG"}, {"name": "thread", "value": "9600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}