{"name": "test01_combo", "status": "failed", "statusDetails": {"message": "Failed", "trace": "self = <test_case.test_calculator.TestCalculator object at 0x000001BB8A4260B0>\n\n    def test01_combo(self):\n>       pytest.fail()\nE       Failed\n\ntest_calculator.py:11: Failed"}, "start": 1640694970563, "stop": 1640694970563, "uuid": "9e25bd9c-aa8c-4cf8-914c-df13d0a7cf05", "historyId": "9c948d6f5db5edbaef64d52f8bbc4041", "testCaseId": "203845d71053675a32f5762b16cf14ee", "fullName": "test_calculator.TestCalculator#test01_combo", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_desktop')"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-2U5JCBG"}, {"name": "thread", "value": "28892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}